/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

/**
 *
 * @author LUID1.7
 */
public class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesquisa = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblNome = new java.awt.Label();
        lblQuantidade = new java.awt.Label();
        lblFornecedor = new java.awt.Label();
        lblRemover = new java.awt.Label();
        btnPesquisar = new javax.swing.JButton();
        btnRemover1 = new javax.swing.JButton();
        btnRemover2 = new javax.swing.JButton();
        btnRemover3 = new javax.swing.JButton();
        btnRemover4 = new javax.swing.JButton();
        btnRemover5 = new javax.swing.JButton();
        btnRemover6 = new javax.swing.JButton();
        btnRemover7 = new javax.swing.JButton();
        btnRemover8 = new javax.swing.JButton();
        btnRemover9 = new javax.swing.JButton();
        btnEditar6 = new javax.swing.JButton();
        btnEditar7 = new javax.swing.JButton();
        btnEditar8 = new javax.swing.JButton();
        btnEditar9 = new javax.swing.JButton();
        lblEditar = new java.awt.Label();
        btnEditar1 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        btnEditar3 = new javax.swing.JButton();
        btnEditar4 = new javax.swing.JButton();
        btnEditar5 = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));

        txtPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 51, 255)));
        txtPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisa.setHighlighter(null);
        jScrollPane1.setViewportView(txtPesquisa);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        lblNome.setAlignment(java.awt.Label.CENTER);
        lblNome.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("NOME");

        lblQuantidade.setAlignment(java.awt.Label.CENTER);
        lblQuantidade.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidade.setText("QUANTIDADE");

        lblFornecedor.setAlignment(java.awt.Label.CENTER);
        lblFornecedor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        lblFornecedor.setText("FORNECEDOR");

        lblRemover.setAlignment(java.awt.Label.CENTER);
        lblRemover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblRemover.setForeground(new java.awt.Color(255, 255, 255));
        lblRemover.setText("REMOVER");

        btnPesquisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Pesquisa.png")); // NOI18N
        btnPesquisar.setBorder(null);
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        btnRemover1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover1.setText("\n");
        btnRemover1.setBorder(null);
        btnRemover1.setContentAreaFilled(false);
        btnRemover1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover1.addActionListener(this::btnRemover1ActionPerformed);

        btnRemover2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover2.setContentAreaFilled(false);
        btnRemover2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover2.addActionListener(this::btnRemover2ActionPerformed);

        btnRemover3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover3.setContentAreaFilled(false);
        btnRemover3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover3.addActionListener(this::btnRemover3ActionPerformed);

        btnRemover4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover4.setContentAreaFilled(false);
        btnRemover4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover4.addActionListener(this::btnRemover4ActionPerformed);

        btnRemover5.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover5.setContentAreaFilled(false);
        btnRemover5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover5.addActionListener(this::btnRemover5ActionPerformed);

        btnRemover6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover6.setContentAreaFilled(false);
        btnRemover6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover6.addActionListener(this::btnRemover6ActionPerformed);

        btnRemover7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover7.setContentAreaFilled(false);
        btnRemover7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover7.addActionListener(this::btnRemover7ActionPerformed);

        btnRemover8.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover8.setContentAreaFilled(false);
        btnRemover8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover8.addActionListener(this::btnRemover8ActionPerformed);

        btnRemover9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Lixeira.png")); // NOI18N
        btnRemover9.setContentAreaFilled(false);
        btnRemover9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover9.addActionListener(this::btnRemover9ActionPerformed);

        btnEditar6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar6.setContentAreaFilled(false);

        btnEditar7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar7.setContentAreaFilled(false);

        btnEditar8.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar8.setContentAreaFilled(false);

        btnEditar9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar9.setContentAreaFilled(false);
        btnEditar9.addActionListener(this::btnEditar9ActionPerformed);

        lblEditar.setAlignment(java.awt.Label.CENTER);
        lblEditar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("EDITAR");

        btnEditar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar1.setBorder(null);
        btnEditar1.setContentAreaFilled(false);
        btnEditar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnEditar2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar2.setContentAreaFilled(false);

        btnEditar3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar3.setContentAreaFilled(false);
        btnEditar3.addActionListener(this::btnEditar3ActionPerformed);

        btnEditar4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar4.setContentAreaFilled(false);

        btnEditar5.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\editarPng.png")); // NOI18N
        btnEditar5.setContentAreaFilled(false);

        btnAdicionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\NetBeansProjects\\prg3persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\Adicionar.png")); // NOI18N
        btnAdicionar.setBorder(null);
        btnAdicionar.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRemover8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRemover2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEditar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(lblRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRemover1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(btnRemover9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover3ActionPerformed

    private void btnRemover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover2ActionPerformed

    private void btnRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover1ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar9ActionPerformed

    private void btnRemover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover9ActionPerformed

    private void btnRemover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover8ActionPerformed

    private void btnRemover7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover7ActionPerformed

    private void btnRemover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover6ActionPerformed

    private void btnRemover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover5ActionPerformed

    private void btnRemover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover4ActionPerformed

    private void btnEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnEditar3;
    private javax.swing.JButton btnEditar4;
    private javax.swing.JButton btnEditar5;
    private javax.swing.JButton btnEditar6;
    private javax.swing.JButton btnEditar7;
    private javax.swing.JButton btnEditar8;
    private javax.swing.JButton btnEditar9;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover1;
    private javax.swing.JButton btnRemover2;
    private javax.swing.JButton btnRemover3;
    private javax.swing.JButton btnRemover4;
    private javax.swing.JButton btnRemover5;
    private javax.swing.JButton btnRemover6;
    private javax.swing.JButton btnRemover7;
    private javax.swing.JButton btnRemover8;
    private javax.swing.JButton btnRemover9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label lblEditar;
    private java.awt.Label lblFornecedor;
    private java.awt.Label lblNome;
    private java.awt.Label lblQuantidade;
    private java.awt.Label lblRemover;
    private javax.swing.JTextPane txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
